# Production Deployment Settings
# All production deployments will use the PROD Environment variables
[context.production.environment]
  GATSBY_ACTIVE_ENV = "production"

# Branch Deployment Settings
# e.g. staging.createdforcrisis.org, development.createdforcrisis.org
# All branch deployments will use the DEV Environment variables
[context.branch-deploy.environment]
  GATSBY_ACTIVE_ENV = "development"

# Netlify Build Plugins
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
