# CircleCI Firebase Deployment Config
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install
            echo 'export CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID' >> $BASH_ENV
            echo 'export CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN' >> $BASH_ENV
      - run:
          name: Gatsby Build
          command: yarn build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
