# CircleCI Firebase Deployment Config
version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: |
            yarn install
            echo 'export CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID' >> $BASH_ENV
            echo 'export CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN' >> $BASH_ENV
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: yarn build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
